blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: ../../../SECURITY.md
    about: Please report security vulnerabilities using GitHub Security Advisory for private disclosure
  - name: Contributing Guide
    url: ../../../CONTRIBUTING.md
    about: Read our contributing guidelines for detailed information about contributions